#!/usr/bin/env bash 
 
# My arch Linux regular package list
# By jmutai
# jmutai.com
#
# set -e
 set -x

echo "" 
 pacaur --needed --noconfirm --noedit -S \
	acpi \
    alsa-tools \
    apache \
	android-file-transfer \
	android-tools \
	android-udev \
    arch-wiki-man \
	atool \
	bash-completion \
    bridge-utils \
    btrfs-progs \
	ccze \
	chrony \
    chromium \
	compton \
    conky \
    cronie \
    curl \
	deepin-screenshot \
	dmenu \
    dnsmasq \
	dosfstools \
    docker \
    docker-compose \
	dunst \
	elinks \
    ebtables \
	eog \
	epdfview \
	feh \
	file-roller \
	gnome-keyring \
	gpicview \
	gvfs-mtp \
	gvim \
	highlight \
	htop \
    httrack \
    iw \
	i3blocks-gaps-git 

 echo "Installing second patch"
pacaur -S --needed --noconfirm --noedit i3-gaps-next-git \
	i3lock-git \
	i3-vim-syntax-git \
    imagemagick \
    iptables \
	j4-dmenu-desktop \
    jq \
	libmtp \
	libnotify \
    lxappearance \
    lm_sensors \
    nvidia \
    nvidia-utils \
    nvidia-settings \
    xorg-server-devel \
    xorg-xinit \
    opencl-nvidia \
	maim \
    masterpdfeditor \
	mediainfo \
	mingetty \
	mlocate \
	mpc \
	mpd \
	mpv \
	msmtp \
	mtpfs  \
	ncmpcpp \
	neomutt-git \
	networkmanager \
	network-manager-applet \
    nemo \
    nemo-fileroller \
    nemo-compare \
    nemo-preview \
    nemo-seahorse \
    nemo-share \
    nemo-terminal \
	nitrogen \
	offlineimap \
	ohsnap \
	openssh \
	openssh \
    openbsd-netcat \
    pepper-flash \
    freshplayerplugin \
	poppler \
    python-pip \
    pinfo \
    pm-utils \
    qemu \
    qbittorrent \
    qutebrowser \
	ranger \
    rar \
	rofi \
	rsync \
	simple-mtpfs \
	slop \
	sysstat \
    startup-notification \
    screenfetch \
    scrot \
    terminator \
	termite-ranger-fix-git \
	thunar \
	thunar-archive-plugin \
    thunar-dropbox \
    thunar-media-tags-plugin \
    upower \
    xdiff-ext-git \
	tk \
	transmission-cli \
	ttf-dejavu \
	ttf-font-awesome \
	ttf-inconsolata \
    powerline-fonts-git \
    pcmanfm-gtk3-git \
	tumbler \
	unzip \
    vsftpd \
    vde2 \
    virt-install \
    virt-manager \
    virt-viewer \
	w3m \
    wget \
    wireless_tools \
	weechat \
	xclip \
	xdotool \
	xorg-xinit \
	xsel \
	youtube-dl \
    zenity \
	zip \
	zsh-completions \
	zathura-epub-git \
	wget

if [ $? -eq 0 ]; then
    echo "Installation successful"
else
    echo "Installation failed"
fi
