#!/usr/bin/env bash 
 
# My arch Linux regular package list
 
 set -e
 dir=$(pwd)

 if [ ! -e "${dir}/${0}" ]; then
     echo ""
     echo " You're in `pwd` "
     echo " Script has to be run within setup directory!!"
     exit 1
 fi  
 
echo ""
#	gtk-engine-murrine-git \
yay --needed --noconfirm  -S \
    faenza-icon-theme \
	gtk-theme-arc-git \
	numix-folders-git \
	numix-icon-theme \
        numix-circle-icon-theme \
	vertex-themes

#numix-themes \
