 pacaur --needed --noconfirm --noedit -S galculator \
    gsimplecal \
    arandr \
    traceroute \
    networkmanager-dmenu-git \
    dunst \
    foxitreader \
    lxappearance-gtk3 \
    networkmanager-openconnect \
    networkmanager-openvpn \
    hipchat \
    wmctrl \
    x11-ssh-askpass \
    xorg-server-devel \
    xorg-xinit \
    ttf-dejavu \
    ttf-font-awesome \
    ttf-monaco \
    ttf-inconsolata \
    ttf-font-icons \
    xclip \
    termite \
    pcmanfm-gtk3 \
    pavucontrol \
    tmux \
    upower \
    scrot \
    screenfetch \
    sysstat \
    slop \
    simple-mtpfs \
    rsync \
    rofi \
    mingetty \
    mlocate \
    mpc \
    mpd \
    mpv \
    msmtp \
    mtpfs \
    mps-youtube \
    libmtp \
    libnotify \
    maim \
    mediainfo \
    keychain \
    httrack \
    iw \
    imagemagick \
    i3pystatus \
    chrony \
    chromium \
    compton \
    bind-tools \
    ccze \
    cronie \
    curl \
    deepin-screenshot \
    dosfstools \
    docker \
    docker-compose \
    docker-machine \
    acpi \
    alsa-tools \
    android-file-transfer \
    android-tools \
    android-udev \
    atool \
    bash-completion \
    ansible \
    gedit \
    glances \
    libx11 \
    libxt \
    keepass \
    freerdp \
    remmina \
    krdc


