 yay --needed --noconfirm  -S \
    galculator \
    nnn \
    fzf \
    pngquant \
    opera \
    xterm \
    lshw \
    fd \
    surf \
    woeusb \
    os-prober \
    axel \
    boostnote \
    gsimplecal \
    arandr \
    traceroute \
    networkmanager-dmenu-git \
    dunst \
    foxitreader \
    lxappearance-gtk3 \
    networkmanager-openconnect \
    networkmanager-openvpn \
    wmctrl \
    x11-ssh-askpass \
    xorg-server-devel \
    xorg-xinit \
    ttf-dejavu \
    ttf-font-awesome \
    ttf-monaco \
    ttf-inconsolata \
    ttf-font-icons \
    xclip \
    termite \
    pcmanfm-gtk3 \
    pavucontrol \
    tmux \
    upower \
    scrot \
    screenfetch \
    sysstat \
    slop \
    simple-mtpfs \
    rsync \
    rofi \
    mingetty \
    mlocate \
    mpc \
    mpd \
    mpv \
    msmtp \
    mtpfs \
    mps-youtube \
    libmtp \
    libnotify \
    maim \
    mediainfo \
    keychain \
    httrack \
    iw \
    imagemagick \
    i3pystatus \
    chrony \
    chromium \
    compton \
    bind-tools \
    ccze \
    cronie \
    curl \
    deepin-screenshot \
    dosfstools \
    docker \
    docker-compose \
    docker-machine \
    acpi \
    alsa-tools \
    android-file-transfer \
    android-tools \
    android-udev \
    atool \
    bash-completion \
    ansible \
    gedit \
    glances \
    libx11 \
    libxt \
    keepass \
    freerdp \
    remmina \
    krdc \
    powertop \
    tp_smapi \
    pwgen \
    xf86-input-wacom \
    udiskie \
    deepin-screenshot \
    acpi_call \
    google-chrome \
    vagrant \
    pcmanfm-qt \
    p7zip \
    file-roller \
    powerline \
    powerline-fonts \
    python-pdftotext \
    emutools \
    transmission-qt \
    odt2txt \
    gpicview \
    nerd-fonts-complete \
    vim-youcompleteme-git

