#!/bin/bash
sudo pip install \
    cs \
    mps-youtube \
    youtube_dl \
    cheat \
    pyalsaaudio \
    netifaces \
    basiciw \
    colour \
    psutil \
    requests  \
    python-language-server \
    mdv \
    git+https://github.com/sivel/speedtest-cli.git@modularize-2 




