#!/usr/bin/env bash

# Some vim packages
pacaur -S  --noedit --noconfirm --needed -S \
    gvim \
    vim-airline \
    vim-fugitive \
    vim-gruvbox-git \
    vim-airline-gruvbox-git \
    vim-youcompleteme-git \
    vim-startify-git \
    vim-tmuxline-git \
    vim-promptline-git  \
    #vim-gitgutter-git 
