#!/bin/env bash

used_ram=`free -h | sed -n '2p' | awk -F' ' '{print $3}'`
total_ram=`free -h | sed -n '2p' | awk -F' ' '{print $2}'`

#echo "<span font='8' font_weight='ultralight' foreground='#B294BB' > </span>$used"
echo "$used_ram/$total_ram"

case $BLOCK_BUTTON in
    1) termite --exec "sh -c 'journalctl -f | ccze -A' --name 'log_term'" ;;
esac
